Repository dapr/docs, pull requests merged in 2020-12, with the labels that each got.

#950 Add Jaeger setup instruction
  daprdocs/content/en/operations/monitoring/jaeger.md
  daprdocs/static/images/jaeger_ui.png
Labels: stale

#940 Update vscode ide information
  daprdocs/content/en/developing-applications/ides/intellij.md
  daprdocs/content/en/developing-applications/ides/vscode-remotecontainers.md
  daprdocs/content/en/developing-applications/ides/vscode.md
Labels: stale

#971 Add postmark as output binding
  daprdocs/content/en/operations/components/setup-bindings/supported-bindings/_index.md
  daprdocs/content/en/operations/components/setup-bindings/supported-bindings/postmark.md
Labels: stale

#985 Added missing word
  daprdocs/content/en/developing-applications/building-blocks/state-management/query-state-store/query-redis-store.md
Labels: content/typo

#986 Fixed a few typos.
  daprdocs/content/en/developing-applications/building-blocks/actors/actors-background.md
Labels: content/typo

#997 Clarifies declarative vs. programmatic pub/sub approach
  daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
Labels: area/runtime/pubsub

#1030 Fix typo in Azure Blob Storage create blob binding
  daprdocs/content/en/operations/components/setup-bindings/supported-bindings/blobstorage.md
Labels: content/typo

#1031 Updating notes for rc.2
  daprdocs/content/en/_index.md
  daprdocs/content/en/getting-started/install-dapr-cli.md
  daprdocs/content/en/getting-started/install-dapr-kubernetes.md
  daprdocs/content/en/getting-started/install-dapr-selfhost.md
Labels: do-not-merge

#1058 Update apns.md
  daprdocs/content/en/operations/components/setup-bindings/supported-bindings/apns.md
Labels: stale
