Repository dapr/docs, pull requests merged in 2020-11, with the labels that each got.

#881 Update secret query example in namespace support
  daprdocs/content/en/reference/api/secrets_api.md
Labels: stale

#926 Website version update
  daprdocs/config.toml
  daprdocs/content/en/_index.md
  daprdocs/content/en/getting-started/configure-redis.md
  daprdocs/content/en/getting-started/install-dapr-cli.md
  daprdocs/content/en/getting-started/install-dapr-kubernetes.md
  daprdocs/content/en/getting-started/install-dapr.md
  daprdocs/content/en/getting-started/quickstarts.md
Labels: do-not-merge

#952 Update azure-keyvault-managed-identity.md
  daprdocs/content/en/operations/components/setup-secret-store/supported-secret-stores/azure-keyvault-managed-identity.md
Labels: content/typo
