Repository dapr/docs, pull requests merged in 2021-12, with the labels that each got.

#2005 Update faq.md to include Go SDK actor availability
  daprdocs/content/en/concepts/faq.md
Labels: stale

#2002 Fix incorrect warning log-level
  daprdocs/content/en/operations/troubleshooting/logs-troubleshooting.md
Labels: stale

#2003 Correct the default component init timeout
  daprdocs/content/en/operations/components/component-schema.md
Labels: stale

#2046 Display state value instead of StateResponse object
  daprdocs/content/en/developing-applications/building-blocks/state-management/howto-get-save-state.md
Labels: stale

#2045 Added missing HTTP verb to the documentation dapr/dapr#4030
  daprdocs/content/en/reference/api/service_invocation_api.md
Labels: stale

#2023 Update logs-troubleshooting.md
  daprdocs/content/en/operations/troubleshooting/logs-troubleshooting.md
Labels: stale

#2061 statestore query api: simplify query JSON
  daprdocs/content/en/developing-applications/building-blocks/state-management/howto-state-query-api.md
  daprdocs/content/en/developing-applications/building-blocks/state-management/query-api-examples/query1.json
  daprdocs/content/en/developing-applications/building-blocks/state-management/query-api-examples/query2.json
  daprdocs/content/en/developing-applications/building-blocks/state-management/query-api-examples/query3-token.json
  daprdocs/content/en/developing-applications/building-blocks/state-management/query-api-examples/query3.json
  daprdocs/content/en/reference/api/state_api.md
Labels: area/runtime/state

#2065 updated RabbitMQ Pub/Sub status
  daprdocs/content/en/reference/components-reference/supported-pubsub/_index.md
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rabbitmq.md
Labels: area/components
