Repository dapr/docs, pull requests merged in 2021-04, with the labels that each got.

#1342 Version mention updates v1.1
  README.md
  daprdocs/content/en/getting-started/install-dapr-selfhost.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-deploy.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-upgrade.md
  daprdocs/content/en/operations/hosting/self-hosted/self-hosted-upgrade.md
  daprdocs/content/en/operations/support/support-release-policy.md
  daprdocs/content/en/reference/cli/dapr-upgrade.md
Labels: do-not-merge

#1328 chore: add documentation on the binding mqtt based on the pubsub mqtt…
  daprdocs/content/en/operations/components/setup-bindings/supported-bindings/mqtt.md
Labels: waiting-on-code-pr

#1334 add pubsub redis config docs
  daprdocs/content/en/operations/components/setup-pubsub/supported-pubsub/setup-redis-pubsub.md
Labels: requested-change, stale

#1398 fix gRPC-integration.md
  daprdocs/content/en/developing-applications/integrations/gRPC-integration.md
Labels: stale

#1432 add redis cluster mode for PubSub component
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-redis-pubsub.md
Labels: waiting-on-code-pr

#1413 Update concepts and add terminology page
  daprdocs/content/en/concepts/components-concept.md
  daprdocs/content/en/concepts/configuration-concept.md
  daprdocs/content/en/concepts/overview.md
  daprdocs/content/en/concepts/terminology.md
  daprdocs/static/images/overview-sidecar-model.png
  daprdocs/static/images/overview_kubernetes.png
  daprdocs/static/images/overview_standalone.png
Labels: stale
