Repository dapr/docs, pull requests merged in 2021-01, with the labels that each got.

#1060 Fix typo in Kubernetes binding docs
  daprdocs/content/en/operations/components/setup-bindings/supported-bindings/kubernetes-binding.md
Labels: stale

#1059 Alphabetically order Microsoft Azure bindings
  daprdocs/content/en/operations/components/setup-bindings/supported-bindings/_index.md
Labels: stale

#1054 Fixing dapr run command in how to get/set state doc (v0.11)
  daprdocs/content/en/developing-applications/building-blocks/state-management/howto-get-save-state.md
Labels: stale

#1080 Add branch guidance
  README.md
  daprdocs/content/en/contributing/contributing-docs.md
Labels: stale

#1092 Documentation for PubSub Message TTL
  daprdocs/content/en/developing-applications/building-blocks/pubsub/pubsub-message-ttl.md
  daprdocs/content/en/reference/api/pubsub_api.md
Labels: area/runtime/pubsub

#1055 Getting started tutorial
  daprdocs/content/en/developing-applications/building-blocks/state-management/howto-get-save-state.md
  daprdocs/content/en/getting-started/_index.md
  daprdocs/content/en/getting-started/configure-state-pubsub.md
  daprdocs/content/en/getting-started/dev-environment.md
  daprdocs/content/en/getting-started/get-started-api.md
  daprdocs/content/en/getting-started/get-started-component.md
  daprdocs/content/en/getting-started/install-dapr-cli.md
  daprdocs/content/en/getting-started/install-dapr-kubernetes.md
  daprdocs/content/en/getting-started/install-dapr-selfhost.md
  daprdocs/content/en/operations/hosting/self-hosted/self-hosted-uninstall.md
  daprdocs/content/en/operations/hosting/self-hosted/self-hosted-upgrade.md
Labels: do-not-merge

#1091 Clarify Service Bus Queues Binding to illustrate that Endpoint= is re…
  daprdocs/content/en/operations/components/setup-bindings/supported-bindings/servicebusqueues.md
Labels: stale
