Repository dapr/docs, pull requests merged in 2021-11, with the labels that each got.

#1926 Release v1.5 (Day of release changes to v1.5)
  .github/workflows/website-root.yml
  README.md
  daprdocs/config.toml
  daprdocs/content/en/operations/support/support-release-policy.md
  daprdocs/layouts/shortcodes/dapr-latest-version.html
Labels: do-not-merge

#1925 Release v1.5 (Day of release changes to v1.4)
  .github/workflows/website-root.yml
  README.md
  daprdocs/config.toml
  daprdocs/content/en/operations/support/support-release-policy.md
Labels: do-not-merge

#1945 fix alpha1 typo for query state api ref
  daprdocs/content/en/reference/api/state_api.md
Labels: content/incorrect-information

#1994 add rel attribute to remove association with previous page
  daprdocs/layouts/partials/navbar.html
  daprdocs/layouts/partials/page-meta-links.html
  daprdocs/layouts/partials/version-banner.html
Labels: stale
