Repository dapr/docs, pull requests merged in 2022-12, with the labels that each got.

#2925 Mark pubsub.hazelcast as deprecated
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-hazelcast.md
  daprdocs/data/components/pubsub/generic.yaml
Labels: stale

#2928 Add nats stream name
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-jetstream.md
Labels: waiting-on-code-pr

#3000 Removing stored procedure references from cosmosDB state store docs
  daprdocs/content/en/reference/components-reference/supported-state-stores/setup-azure-cosmosdb.md
Labels: area/components
