Repository dapr/docs, pull requests merged in 2022-04, with the labels that each got.

#2252 Update resource name in pubsub to be valid
  daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
Labels: stale

#2295 Adding docs for dapr init changes
  daprdocs/content/en/operations/support/support-preview-features.md
  daprdocs/content/en/reference/cli/dapr-init.md
  daprdocs/content/en/reference/environment/_index.md
Labels: area/cli

#2301 Airgap installer changes in docs
  daprdocs/content/en/operations/hosting/self-hosted/self-hosted-airgap.md
  daprdocs/content/en/operations/hosting/self-hosted/self-hosted-overview.md
  daprdocs/content/en/reference/cli/dapr-init.md
Labels: P0

#2328 Updated Cosmos DB docs for Dapr 1.7
  daprdocs/content/en/reference/components-reference/supported-bindings/cosmosdb.md
  daprdocs/content/en/reference/components-reference/supported-state-stores/setup-azure-cosmosdb.md
Labels: area/runtime/state

#2322 Provide monitoring instructions for Dapr root certificate expiration
  daprdocs/content/en/operations/security/mtls.md
Labels: P0

#2327 Update EventHubs docs for AAD authentication
  daprdocs/content/en/reference/components-reference/supported-bindings/eventhubs.md
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-azure-eventhubs.md
Labels: P0

#2293 Adding documentation for certificate renewal
  daprdocs/content/en/operations/security/mtls.md
  daprdocs/content/en/reference/cli/dapr-components.md
  daprdocs/content/en/reference/cli/dapr-configurations.md
  daprdocs/content/en/reference/cli/dapr-dashboard.md
  daprdocs/content/en/reference/cli/dapr-list.md
  daprdocs/content/en/reference/cli/dapr-logs.md
  daprdocs/content/en/reference/cli/dapr-mtls/_index.md
  daprdocs/content/en/reference/cli/dapr-mtls/dapr-mtls-expiry.md
  daprdocs/content/en/reference/cli/dapr-mtls/dapr-mtls-export.md
  daprdocs/content/en/reference/cli/dapr-mtls/dapr-mtls-renew-certificate.md
  daprdocs/content/en/reference/cli/dapr-status.md
  daprdocs/content/en/reference/cli/dapr-upgrade.md
Labels: P0

#2305 Using redislabs/rejson with query api
  daprdocs/content/en/reference/components-reference/supported-state-stores/setup-redis.md
Labels: P0, area/runtime/state

#2337 Document Azure ServiceBus params for AAD auth
  daprdocs/content/en/reference/components-reference/supported-bindings/servicebusqueues.md
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-azure-eventhubs.md
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-azure-servicebus.md
Labels: P0

#2352 Fixes state-store-ttl Python example
  daprdocs/content/en/developing-applications/building-blocks/pubsub/pubsub-raw.md
  daprdocs/content/en/developing-applications/building-blocks/state-management/state-store-ttl.md
Labels: area/runtime/pubsub, area/runtime/state

#2367 [dapr init] add new flags and examples to docs
  daprdocs/content/en/reference/cli/dapr-init.md
Labels: stale

#2350 [nats streaming pub/sub] fix parameter typo
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-nats-streaming.md
Labels: stale

#2349 [metrics] fix code snippet typo
  daprdocs/content/en/operations/monitoring/metrics/metrics-overview.md
Labels: stale

#2400 Target of dapr annotations (pod) described more clearly
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-overview.md
Labels: platform/Kubernetes

#2402 Add profile-port to env variables table
  daprdocs/content/en/reference/components-reference/supported-state-stores/setup-sqlserver.md
  daprdocs/content/en/reference/environment/_index.md
Labels: content/missing-information
