Repository dapr/docs, pull requests merged in 2022-03, with the labels that each got.

#2223 Update get-started-component.md
  daprdocs/content/en/getting-started/get-started-component.md
Labels: area/cli

#2204 Jetstream statestore and auth
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-jetstream.md
  daprdocs/content/en/reference/components-reference/supported-state-stores/_index.md
  daprdocs/content/en/reference/components-reference/supported-state-stores/setup-jetstream-kv.md
Labels: stale

#2224 Improving the Security concepts overviews
  daprdocs/content/en/concepts/security-concept.md
  daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-namespaces.md
  daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-overview.md
  daprdocs/content/en/developing-applications/building-blocks/state-management/howto-encrypt-state.md
  daprdocs/content/en/operations/components/component-scopes.md
  daprdocs/content/en/operations/security/mtls.md
  daprdocs/static/images/pubsub-multiple-namespaces.png
  daprdocs/static/images/security-dapr-API-scoping.png
  daprdocs/static/images/security-end-to-end-communication.png
  daprdocs/static/images/security-mTLS-dapr-system-services.png
  daprdocs/static/images/security-mTLS-sentry-kubernetes.png
  daprdocs/static/images/security-mTLS-sentry-selfhosted.png
  daprdocs/static/images/security-overview-capabilities-example.png
Labels: area/security

#2231 Fix alignment in kubectl output
  daprdocs/content/en/getting-started/configure-state-pubsub.md
Labels: area/runtime/pubsub

#2217 New Quickstarts for PubSub and Service Invocation
  daprdocs/content/en/developing-applications/building-blocks/bindings/bindings-overview.md
  daprdocs/content/en/developing-applications/building-blocks/bindings/howto-bindings.md
  daprdocs/content/en/developing-applications/building-blocks/observability/w3c-tracing/w3c-tracing-howto.md
  daprdocs/content/en/developing-applications/building-blocks/observability/w3c-tracing/w3c-tracing-overview.md
  daprdocs/content/en/developing-applications/building-blocks/pubsub/howto-publish-subscribe.md
  daprdocs/content/en/developing-applications/building-blocks/pubsub/pubsub-overview.md
  daprdocs/content/en/developing-applications/building-blocks/secrets/howto-secrets.md
  daprdocs/content/en/developing-applications/building-blocks/service-invocation/service-invocation-overview.md
  daprdocs/content/en/developing-applications/building-blocks/state-management/state-management-overview.md
  daprdocs/content/en/developing-applications/debugging/bridge-to-kubernetes.md
  daprdocs/content/en/developing-applications/debugging/debug-k8s/debug-dapr-services.md
  daprdocs/content/en/developing-applications/debugging/debug-k8s/debug-daprd.md
  daprdocs/content/en/developing-applications/ides/vscode/vscode-how-to-debug-multiple-dapr-apps.md
  daprdocs/content/en/developing-applications/ides/vscode/vscode-remote-dev-containers.md
  daprdocs/content/en/getting-started/_index.md
  daprdocs/content/en/getting-started/configure-state-pubsub.md
  daprdocs/content/en/getting-started/get-started-api.md
  daprdocs/content/en/getting-started/get-started-component.md
  daprdocs/content/en/getting-started/install-dapr-cli.md
  daprdocs/content/en/getting-started/install-dapr-selfhost.md
  daprdocs/content/en/getting-started/quickstarts.md
  daprdocs/content/en/getting-started/quickstarts/_index.md
  daprdocs/content/en/getting-started/quickstarts/pubsub-quickstart.md
  daprdocs/content/en/getting-started/quickstarts/serviceinvocation-quickstart.md
  daprdocs/content/en/getting-started/tutorials/_index.md
  daprdocs/content/en/getting-started/tutorials/configure-state-pubsub.md
  daprdocs/content/en/getting-started/tutorials/get-started-component.md
  daprdocs/content/en/operations/components/setup-pubsub/_index.md
  daprdocs/content/en/operations/components/setup-pubsub/pubsub-namespaces.md
  daprdocs/content/en/operations/configuration/invoke-allowlist.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-deploy.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-overview.md
  daprdocs/content/en/operations/monitoring/tracing/open-telemetry-collector-appinsights.md
  daprdocs/content/en/operations/monitoring/tracing/open-telemetry-collector.md
  daprdocs/content/en/reference/api/pubsub_api.md
  daprdocs/static/images/install-dapr-selfhost/docker-containers.png
  daprdocs/static/images/install-dapr-selfhost/windows-view-components.png
  daprdocs/static/images/pubsub-quickstart/pubsub-diagram.png
  daprdocs/static/images/pubsub-quickstart/pubsub-dotnet-publisher-output.png
  daprdocs/static/images/pubsub-quickstart/pubsub-dotnet-subscriber-output.png
  daprdocs/static/images/pubsub-quickstart/pubsub-java-publisher-output.png
  daprdocs/static/images/pubsub-quickstart/pubsub-java-subscriber-output.png
  daprdocs/static/images/pubsub-quickstart/pubsub-js-publisher-output.png
  daprdocs/static/images/pubsub-quickstart/pubsub-js-subscriber-output.png
  daprdocs/static/images/pubsub-quickstart/pubsub-python-publisher-output.png
  daprdocs/static/images/pubsub-quickstart/pubsub-python-subscriber-output.png
  daprdocs/static/images/serviceinvocation-quickstart/service-invocation-overview.png
Labels: do-not-merge

#2262 add documentation for new metadata fields maxReconnectionAttempts and connectionRecoveryInSec in GCP pub/sub component
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-gcp-pubsub.md
Labels: stale

#2287 fix: Getting started / Init Dapr locally has wrong quickstarts link
  daprdocs/content/en/getting-started/install-dapr-selfhost.md
Labels: P0

#2308 Changed api logging feature - docs
  daprdocs/content/en/operations/monitoring/logging/logs.md
  daprdocs/content/en/operations/troubleshooting/api-logs-troubleshooting.md
  daprdocs/content/en/reference/arguments-annotations-overview.md
  daprdocs/content/en/reference/cli/dapr-run.md
Labels: area/observability

#1749 Add namespace flag option to "components", "configurations" and "list" CLI commands
  daprdocs/content/en/reference/cli/dapr-components.md
  daprdocs/content/en/reference/cli/dapr-configurations.md
  daprdocs/content/en/reference/cli/dapr-list.md
Labels: P0
