Repository dapr/docs, pull requests merged in 2022-09, with the labels that each got.

#2726 Typo fix installtion > installation
  daprdocs/content/en/operations/components/component-secrets.md
Labels: stale

#2811 fix the example code
  daprdocs/content/en/reference/components-reference/supported-middleware/middleware-wasm.md
Labels: stale

#2725 Update go commands to match quickstarts
  daprdocs/content/en/concepts/overview.md
  daprdocs/content/en/getting-started/quickstarts/bindings-quickstart.md
  daprdocs/content/en/getting-started/quickstarts/pubsub-quickstart.md
  daprdocs/content/en/getting-started/quickstarts/secrets-quickstart.md
  daprdocs/content/en/getting-started/quickstarts/serviceinvocation-quickstart.md
  daprdocs/content/en/getting-started/quickstarts/statemanagement-quickstart.md
Labels: stale

#2830 Updated azure app config metadata fields name
  daprdocs/content/en/reference/components-reference/supported-configuration-stores/azure-appconfig-configuration-store.md
  daprdocs/data/components/configuration_stores/generic.yaml
Labels: area/components

#2817 Add note for sidecar readiness
  daprdocs/content/en/concepts/dapr-services/sidecar.md
  daprdocs/content/en/developing-applications/building-blocks/observability/sidecar-health.md
Labels: area/observability
