Repository dapr/docs, pull requests merged in 2023-09, with the labels that each got.

#3686 [resource specs] Cross link
  daprdocs/content/en/developing-applications/building-blocks/service-invocation/howto-invoke-non-dapr-endpoints.md
  daprdocs/content/en/reference/resource-specs/component-schema.md
  daprdocs/content/en/reference/resource-specs/httpendpoints-schema.md
Labels: stale

#3689 [K8s hosting] Refresh and address older issues
  daprdocs/content/en/operations/configuration/configuration-overview.md
  daprdocs/content/en/operations/hosting/kubernetes/cluster/setup-aks.md
  daprdocs/content/en/operations/hosting/kubernetes/cluster/setup-gke.md
  daprdocs/content/en/operations/hosting/kubernetes/cluster/setup-kind.md
  daprdocs/content/en/operations/hosting/kubernetes/cluster/setup-minikube.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-deploy.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-hybrid-clusters.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-job.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-overview.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-production.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-upgrade.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-volume-mounts.md
  daprdocs/content/en/operations/hosting/self-hosted/self-hosted-with-docker.md
  daprdocs/content/en/operations/hosting/self-hosted/self-hosted-with-podman.md
  daprdocs/content/en/operations/observability/_index.md
  daprdocs/content/en/reference/resource-specs/configuration-schema.md
Labels: stale

#3682 Add subscriptions to metadata API reference examples
  daprdocs/content/en/reference/api/metadata_api.md
Labels: area/runtime/metadata

#3655 Reference: pubsub pulsar OIDC authentication
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-pulsar.md
Labels: area/components

#3631 Add placement table api doc
  daprdocs/content/en/concepts/dapr-services/placement.md
Labels: platform/Kubernetes

#3699 Create 'quorum' queues in RabbitMQ
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rabbitmq.md
Labels: stale

#3662 [docs] Workflow docs for Java SDK
  daprdocs/content/en/concepts/building-blocks-concept.md
  daprdocs/content/en/developing-applications/building-blocks/workflow/howto-author-workflow.md
  daprdocs/content/en/developing-applications/building-blocks/workflow/howto-manage-workflow.md
  daprdocs/content/en/developing-applications/building-blocks/workflow/workflow-architecture.md
  daprdocs/content/en/developing-applications/building-blocks/workflow/workflow-features-concepts.md
  daprdocs/content/en/developing-applications/building-blocks/workflow/workflow-overview.md
  daprdocs/content/en/developing-applications/building-blocks/workflow/workflow-patterns.md
  daprdocs/content/en/getting-started/quickstarts/workflow-quickstart.md
  daprdocs/content/en/operations/support/alpha-beta-apis.md
  daprdocs/content/en/reference/api/workflow_api.md
Labels: P0

#3745 Add Placement API topic
  daprdocs/content/en/concepts/dapr-services/placement.md
  daprdocs/content/en/reference/api/error_codes.md
  daprdocs/content/en/reference/api/placement_api.md
  daprdocs/content/en/reference/environment/_index.md
Labels: P0, area/runtime/actor

#3727 Jaeger OpenTelemetry docs
  daprdocs/content/en/operations/observability/tracing/jaeger.md
  daprdocs/content/en/operations/observability/tracing/otel-collector/open-telemetry-collector-jaeger.md
  daprdocs/content/en/operations/observability/tracing/otel-collector/open-telemetry-collector.md
  daprdocs/content/en/operations/observability/tracing/setup-tracing.md
  daprdocs/static/docs/open-telemetry-collector/collector-config-otel.yaml
  daprdocs/static/docs/open-telemetry-collector/open-telemetry-collector-jaeger.yaml
Labels: P1, area/observability
