Repository dapr/docs, pull requests merged in 2024-02, with the labels that each got.

#3992 Add Kafka AWS IAM support for authenication
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-apache-kafka.md
Labels: area/runtime/pubsub

#4008 Workflow terminate/purge: remove `non_recursive` query option
  daprdocs/content/en/developing-applications/building-blocks/workflow/workflow-features-concepts.md
  daprdocs/content/en/reference/api/workflow_api.md
Labels: waiting-on-code-pr, area/workflow

#3947 Added .NET examples for encryption and decryption to Cryptography how-to
  daprdocs/content/en/developing-applications/building-blocks/cryptography/howto-cryptography.md
Labels: P1

#4027 Hot reloading: add notes about the behaviour and exceptions
  daprdocs/content/en/operations/components/component-updates.md
  daprdocs/content/en/operations/support/support-preview-features.md
Labels: waiting-on-code-pr

#3843 Added example for retrieving bulk deserialized items in dotnet-sdk repo
  daprdocs/content/en/developing-applications/building-blocks/state-management/howto-get-save-state.md
Labels: P2
