Repository dapr/docs, pull requests merged in 2024-07, with the labels that each got.

#4257 [Outbox] Format message structure sent
  daprdocs/content/en/developing-applications/building-blocks/state-management/howto-outbox.md
Labels: P0

#4259 Add Rabbitmq single active consumer parameter
  daprdocs/content/en/reference/components-reference/supported-pubsub/setup-rabbitmq.md
Labels: P0

#4256 Updates API ref for jobs. Adds doc on Kubernetes Scheduler persistent
  daprdocs/content/en/developing-applications/building-blocks/jobs/howto-schedule-jobs.md
  daprdocs/content/en/developing-applications/building-blocks/jobs/jobs-overview.md
  daprdocs/content/en/operations/hosting/kubernetes/kubernetes-persisting-scheduler.md
  daprdocs/content/en/operations/hosting/self-hosted/self-hosted-persisting-scheduler.md
  daprdocs/content/en/reference/api/jobs_api.md
  daprdocs/content/en/reference/cli/dapr-init.md
Labels: do-not-merge

#4243 Jobs API docs, pt 3
  daprdocs/content/en/developing-applications/building-blocks/jobs/howto-schedule-and-handle-triggered-jobs.md
  daprdocs/content/en/developing-applications/building-blocks/jobs/howto-schedule-jobs.md
  daprdocs/content/en/developing-applications/building-blocks/jobs/jobs-overview.md
  daprdocs/content/en/getting-started/install-dapr-selfhost.md
  daprdocs/content/en/reference/cli/dapr-uninstall.md
  daprdocs/static/images/install-dapr-selfhost/dapr-init-output.png
  daprdocs/static/images/install-dapr-selfhost/docker-containers.png
Labels: P0

#4276 jobs quickstart
  daprdocs/content/en/getting-started/quickstarts/jobs-quickstart.md
Labels: waiting-on-code-pr
