Repository dapr/docs, pull requests merged in 2024-01, with the labels that each got.

#3952 Added Crypto API reference documentation
  daprdocs/content/en/developing-applications/building-blocks/cryptography/cryptography-overview.md
  daprdocs/content/en/reference/api/cryptography_api.md
  daprdocs/content/en/reference/api/error_codes.md
Labels: P1, content/missing-information, area/cryptography

#3908 Error codes
  daprdocs/content/en/reference/errors/_index.md
Labels: P1

#3970 Add Instructions to add Kubernetes Metrics server to Kind
  daprdocs/content/en/operations/hosting/kubernetes/cluster/setup-kind.md
Labels: do-not-merge

#3966 Update step 5 of pubsub-quickstart.md
  daprdocs/content/en/getting-started/quickstarts/pubsub-quickstart.md
Labels: P2
